#!/bin/sh

PDF_SIZE_OFFSET=902
PDF_OFFSET=$((PDF_SIZE_OFFSET + 4))
usage() {
	echo "usage: $0 <original pdf image>" >&2
	exit 1
}
[[ $# == 1 ]] || usage

PDF_SIZE="$(dd if=$1 bs=1 skip=$PDF_SIZE_OFFSET count=4 2>/dev/null | hexdump -e '1/4 "%d\n"')"
echo "PDF is $PDF_SIZE bytes"

mount -t tmpfs tmpfs /overlay
mkdir /overlay/root /overlay/work
mount -t overlay overlay -o lowerdir=/base,upperdir=/overlay/root,workdir=/overlay/work /newroot
losetup -o $PDF_OFFSET /dev/loop1 $1
dd if=/dev/loop1 bs=$PDF_SIZE count=1 of=/newroot/embedded.pdf 2>/dev/null

mount -t proc -o noexec,nosuid,nodev proc /newroot/proc
mount -t sysfs -o noexec,nosuid,nodev sysfs /newroot/sys
mount -t devtmpfs devtmpfs -o exec,nosuid,mode=0755,size=2M /newroot/dev

# ptys
[ -c /newroot/dev/ptmx ] || mknod -m 666 /newroot/dev/ptmx c 5 2
[ -d /newroot/dev/pts ] || mkdir -m 755 /newroot/dev/pts
mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /newroot/dev/pts

# shm
[ -d /newroot/dev/shm ] || mkdir /newroot/dev/shm
mount -t tmpfs -o nodev,nosuid,noexec shm /newroot/dev/shm

mount -t tmpfs tmpfs /newroot/tmp

exec switch_root /newroot /sbin/init
