#!/bin/sh

mupdf-x11 /embedded.pdf &

WIDTH="$(xwininfo -root | grep Width | awk '{ print $2 }')"
HEIGHT="$(xwininfo -root | grep Height | awk '{ print $2 }')"
xmessage -center -buttons OK -file /etc/xwelcome
xdotool search --sync --class "mupdf" windowsize $WIDTH $HEIGHT windowmove 0 0

wait
